apiVersion: v1
kind: Service
metadata:
  name: opensearchapi-service
spec:
  type: NodePort
  selector:
    app: opensearchapi
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearchapi-deployment
  labels:
    app: opensearchapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearchapi
  template:
    metadata:
      labels:
        app: opensearchapi
    spec:
      containers:
      - name: opensearchapi
        image: mabarraza/opensearch-api:1.0
        ports:
        - containerPort: 4040

